# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'Компоновање рачунарских програма'
copyright = '2020-2021, Владимир Миловановић'
author = 'Владимир Миловановић'

# The short X.Y version
version = ''
# The full version, including alpha/beta/rc tags
release = 'прво штампано'


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
#extensions = [
#]
extensions = ['sphinx.ext.coverage', 'sphinx.ext.doctest']#, 'sphinxcontrib.tikz']#,
#              'pyspecific', 'c_annotations', 'escape4chm']

doctest_global_setup = '''
try:
    import _tkinter
except ImportError:
    _tkinter = None
'''

# Enable warnings for all bad cross references. These are turned into errors
# with the -W flag in the Makefile.
nitpicky = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'
# latex_doc = 'lindex'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'sr'

today = '2021.'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

#[restructuredtext parser]
#syntax_highlight = short

# -- Options for HTML output -------------------------------------------------

def setup(app):
    app.add_js_file('copybutton.js')

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'agogo'
html_theme = 'alabaster'
html_theme = 'classic'
html_theme = 'nature'
html_theme = 'pyramid'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'KomRaProg'

# -- Options for LaTeX output ------------------------------------------------

CCBYSAlogo = './LaTeXcustom/by-sa.eps'

latex_additional_files = [CCBYSAlogo]
latex_engine = 'pdflatex'
latex_elements = {
    'extrapackages': r'\usepackage{CJKutf8}\usepackage{tikz}\usetikzlibrary{automata}',  # for title-page
    'fncychap': r'\usepackage[Bjornstrup]{fncychap}',
    #'fncychap': r'\usepackage[Lenny]{fncychap}',
    'figure_align': 'htbp',
    'fontenc': r'\usepackage[T2A,T1]{fontenc}',
    'fontpkg': r'''
     \usepackage{lmodern}
     \substitutefont{T2A}{\rmdefault}{cmr}
     \substitutefont{T2A}{\sfdefault}{cmss}
     \substitutefont{T2A}{\ttdefault}{cmtt}
    ''',
    'fvset': r'\fvset{fontsize=\small}', # or fontsize=auto
    'geometry': r'\usepackage[paperwidth=170mm,paperheight=240mm]{geometry}',
    'inputenc': r'\usepackage[utf8]{inputenc}',
    #'maketitle': '\\cover',
    #'maketitle':r'\newcommand\sphinxbackoftitlepage{<Extra material>}\sphinxmaketitle',
    'maketitle': r'''
     \newcommand\sphinxbackoftitlepage{
     \noindent\sphinxstylestrong{Аутор}:\newline
     др Владимир М. Миловановић, доцент\newline
     Факултет инжењерских наука, Универзитет у Крагујевцу\newline
     {\large\Letter} \href{mailto:vlada@kg.ac.rs}{\nolinkurl{vlada@kg.ac.rs}}

     \bigskip
     \vspace{7pt}\noindent\rule{\textwidth}{1pt}\vspace{7pt}
     \centerline{\large{\MakeUppercase{\sphinxstylestrong{Компоновање рачунарских програма}}}}
     \vspace{7pt}\noindent\rule{\textwidth}{1pt}\vspace{7pt}

     \bigskip
     \noindent\sphinxstylestrong{Издавач}:\newline
     Факултет инжењерских наука у Крагујевцу\newline
     Сестре Јањић 6, 34000 Крагујевац, Србија

     \smallskip
     \noindent\sphinxstylestrong{За издавача}:\newline
     проф. др Добрица Миловановић, декан

     \medskip
     \noindent\sphinxstylestrong{Рецензенти}:\newline
     др Предраг Пејовић, редовни професор\newline
     др Александар Пеулић, редовни професор

     \medskip
     \vspace{7pt}\noindent\hrulefill\vspace{7pt}\newline
     \noindentОдлуком Наставно\sphinxhyphen{}научног већа Факултета инжењерских наука број 01-1/406-12 од 18. фебруара 2021. године ова књига одобрена је као основни универзитетски уџбеник.
     \vspace{7pt}\noindent\hrulefill\vspace{7pt}

     \medskip
     \noindent\sphinxstylestrong{Штампа}:\newline
     СЗР Графички центар \textsl{Интерпринт}, Крагујевац, 2021.

     \smallskip
     \noindent\sphinxstylestrong{Тираж}:\newline
     100 примерака

     \vfill
     \noindent\sphinxstylestrong{ISBN}: 978-86-6335-081-6\newline

     \bigskip
     \sphinxincludegraphics{{by-sa}.eps}
     Нека права задржана. Ово дело објављено је под условима Кријејтив комонс Ауторство\sphinxhyphen{}делити под истим условима 4.0 међународне лиценце (енг. \sphinxhref{http://creativecommons.org/licenses/by-sa/4.0}{Creative Commons Attribution\sphinxhyphen{}ShareAlike 4.0 International License} --- CC BY\sphinxhyphen{}SA).
     }\sphinxmaketitle
     \begin{CJK}{UTF8}{min}
    ''',
    'atendofbody': r'\end{CJK}',
    # The paper size ('a4paper', 'b5paper' or 'letterpaper').
    #
    #'papersize': 'a4paper',
    'papersize': 'b5paper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    #'babel': r'\usepackage[serbian]{babel}',
    'preamble': r'''
     \usepackage{marvosym}
     %\usepackage{txfonts}
     \DeclareUnicodeCharacter{2660}{$\spadesuit$}
     \DeclareUnicodeCharacter{2661}{$\heartsuit$}
     \DeclareUnicodeCharacter{2662}{$\diamondsuit$}
     \DeclareUnicodeCharacter{2663}{$\clubsuit$}
     \DeclareUnicodeCharacter{2664}{$\varspadesuit$}
     \DeclareUnicodeCharacter{2665}{$\varheartsuit$}
     \DeclareUnicodeCharacter{2666}{$\vardiamondsuit$}
     \DeclareUnicodeCharacter{2667}{$\varclubsuit$}
    ''',
    'releasename': 'издање:',
    'printindex': r'\printindex',
    #'printindex': r'\footnotesize\raggedright\printindex',
    #'sphinxsetup': 'hmargin=55pt, vmargin=69pt', # this is for ISO b5paper 176 × 250 mm^2
    'sphinxsetup': 'hmargin=48pt, vmargin=69pt', # this is for custom B5 170 × 240 mm^2
}

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#
# latex_logo = None
latex_logo = './LaTeXcustom/bookwheel.jpg'

# If true, show page references after internal links.
#
latex_show_pagerefs = True

# If true, show URL addresses after external links.
#
latex_show_urls = 'footnote' # = 'inline' # = 'no'

# We use False otherwise the module index gets generated twice.
latex_use_modindex = True

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [(master_doc, 'КРП.tex', 'Компоновање рачунарских програма', 'Владимир Миловановић', 'manual', True)]

# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, 'KomRaProg', 'Компоновање рачунарских програма', [author], 1)]

# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'KomRaProg', 'Компоновање рачунарских програма', author,
     'KomRaProg', 'One line description of project.', 'Miscellaneous'),
]
